<?php

return [
    ['country' => 'Afeganistão', 'capital' => 'Cabul'],
    ['country' => 'Albânia', 'capital' => 'Tirana'],
    ['country' => 'Alemanha', 'capital' => 'Berlim'],
    ['country' => 'Andorra', 'capital' => 'Andorra-a-Velha'],
    ['country' => 'Angola', 'capital' => 'Luanda'],
    ['country' => 'Antígua e Barbuda', 'capital' => 'Saint John’s'],
    ['country' => 'Arábia Saudita', 'capital' => 'Riad'],
    ['country' => 'Argélia', 'capital' => 'Argel'],
    ['country' => 'Argentina', 'capital' => 'Buenos Aires'],
    ['country' => 'Armênia', 'capital' => 'Erevã'],
    ['country' => 'Austrália', 'capital' => 'Canberra'],
    ['country' => 'Áustria', 'capital' => 'Viena'],
    ['country' => 'Azerbaijão', 'capital' => 'Bacu'],
    ['country' => 'Bahamas', 'capital' => 'Nassau'],
    ['country' => 'Bahrein', 'capital' => 'Manama'],
    ['country' => 'Bangladesh', 'capital' => 'Daca'],
    ['country' => 'Barbados', 'capital' => 'Bridgetown'],
    ['country' => 'Bélgica', 'capital' => 'Bruxelas'],
    ['country' => 'Belize', 'capital' => 'Belmopan'],
    ['country' => 'Benin', 'capital' => 'Porto-Novo'],
    ['country' => 'Bolívia', 'capital' => 'Sucre'],
    ['country' => 'Bósnia e Herzegovina', 'capital' => 'Sarajevo'],
    ['country' => 'Botsuana', 'capital' => 'Gaborone'],
    ['country' => 'Brasil', 'capital' => 'Brasília'],
    ['country' => 'Brunei', 'capital' => 'Bandar Seri Begawan'],
    ['country' => 'Bulgária', 'capital' => 'Sófia'],
    ['country' => 'Burkina Faso', 'capital' => 'Uagadugu'],
    ['country' => 'Burundi', 'capital' => 'Gitega'],
    ['country' => 'Butão', 'capital' => 'Thimphu'],
    ['country' => 'Cabo Verde', 'capital' => 'Praia'],
    ['country' => 'Camarões', 'capital' => 'Yaoundé'],
    ['country' => 'Camboja', 'capital' => 'Phnom Penh'],
    ['country' => 'Canadá', 'capital' => 'Ottawa'],
    ['country' => 'Catar', 'capital' => 'Doha'],
    ['country' => 'Cazaquistão', 'capital' => 'Astana'],
    ['country' => 'Chade', 'capital' => 'N’Djamena'],
    ['country' => 'Chile', 'capital' => 'Santiago'],
    ['country' => 'China', 'capital' => 'Pequim'],
    ['country' => 'Chipre', 'capital' => 'Nicósia'],
    ['country' => 'Colômbia', 'capital' => 'Bogotá'],
    ['country' => 'Comores', 'capital' => 'Moroni'],
    ['country' => 'Congo', 'capital' => 'Brazzaville'],
    ['country' => 'Coreia do Norte', 'capital' => 'Pyongyang'],
    ['country' => 'Coreia do Sul', 'capital' => 'Seul'],
    ['country' => 'Costa do Marfim', 'capital' => 'Yamoussoukro'],
    ['country' => 'Costa Rica', 'capital' => 'San José'],
    ['country' => 'Croácia', 'capital' => 'Zagreb'],
    ['country' => 'Cuba', 'capital' => 'Havana'],
    ['country' => 'Dinamarca', 'capital' => 'Copenhague'],
    ['country' => 'Djibouti', 'capital' => 'Djibouti'],
    ['country' => 'Dominica', 'capital' => 'Roseau'],
    ['country' => 'Egito', 'capital' => 'Cairo'],
    ['country' => 'El Salvador', 'capital' => 'San Salvador'],
    ['country' => 'Emirados Árabes Unidos', 'capital' => 'Abu Dhabi'],
    ['country' => 'Equador', 'capital' => 'Quito'],
    ['country' => 'Eritreia', 'capital' => 'Asmara'],
    ['country' => 'Eslováquia', 'capital' => 'Bratislava'],
    ['country' => 'Eslovênia', 'capital' => 'Liubliana'],
    ['country' => 'Espanha', 'capital' => 'Madri'],
    ['country' => 'Estados Unidos', 'capital' => 'Washington, D.C.'],
    ['country' => 'Estônia', 'capital' => 'Tallinn'],
    ['country' => 'Etiópia', 'capital' => 'Adis Abeba'],
    ['country' => 'Fiji', 'capital' => 'Suva'],
    ['country' => 'Filipinas', 'capital' => 'Manila'],
    ['country' => 'Finlândia', 'capital' => 'Helsinque'],
    ['country' => 'França', 'capital' => 'Paris'],
    ['country' => 'Gabão', 'capital' => 'Libreville'],
    ['country' => 'Gâmbia', 'capital' => 'Banjul'],
    ['country' => 'Gana', 'capital' => 'Acra'],
    ['country' => 'Geórgia', 'capital' => 'Tbilisi'],
    ['country' => 'Granada', 'capital' => 'Saint George’s'],
    ['country' => 'Grécia', 'capital' => 'Atenas'],
    ['country' => 'Guatemala', 'capital' => 'Cidade da Guatemala'],
    ['country' => 'Guiana', 'capital' => 'Georgetown'],
    ['country' => 'Guiné', 'capital' => 'Conacri'],
    ['country' => 'Guiné-Bissau', 'capital' => 'Bissau'],
    ['country' => 'Guiné Equatorial', 'capital' => 'Malabo'],
    ['country' => 'Haiti', 'capital' => 'Porto Príncipe'],
    ['country' => 'Honduras', 'capital' => 'Tegucigalpa'],
    ['country' => 'Hungria', 'capital' => 'Budapeste'],
    ['country' => 'Iêmen', 'capital' => 'Sanaá'],
    ['country' => 'Índia', 'capital' => 'Nova Délhi'],
    ['country' => 'Indonésia', 'capital' => 'Jacarta'],
    ['country' => 'Irã', 'capital' => 'Teerã'],
    ['country' => 'Iraque', 'capital' => 'Bagdá'],
    ['country' => 'Irlanda', 'capital' => 'Dublin'],
    ['country' => 'Islândia', 'capital' => 'Reykjavík'],
    ['country' => 'Israel', 'capital' => 'Jerusalém'],
    ['country' => 'Itália', 'capital' => 'Roma'],
    ['country' => 'Jamaica', 'capital' => 'Kingston'],
    ['country' => 'Japão', 'capital' => 'Tóquio'],
    ['country' => 'Jordânia', 'capital' => 'Amã'],
    ['country' => 'Laos', 'capital' => 'Vientiane'],
    ['country' => 'Letônia', 'capital' => 'Riga'],
    ['country' => 'Líbano', 'capital' => 'Beirute'],
    ['country' => 'Libéria', 'capital' => 'Monróvia'],
    ['country' => 'Líbia', 'capital' => 'Trípoli'],
    ['country' => 'Liechtenstein', 'capital' => 'Vaduz'],
    ['country' => 'Lituânia', 'capital' => 'Vilnius'],
    ['country' => 'Luxemburgo', 'capital' => 'Luxemburgo'],
    ['country' => 'Macedônia do Norte', 'capital' => 'Skopje'],
    ['country' => 'Madagascar', 'capital' => 'Antananarivo'],
    ['country' => 'Malásia', 'capital' => 'Kuala Lumpur'],
    ['country' => 'Malawi', 'capital' => 'Lilongwe'],
    ['country' => 'Maldivas', 'capital' => 'Malé'],
    ['country' => 'Mali', 'capital' => 'Bamaco'],
    ['country' => 'Malta', 'capital' => 'Valletta'],
    ['country' => 'Marrocos', 'capital' => 'Rabat'],
    ['country' => 'México', 'capital' => 'Cidade do México'],
    ['country' => 'Moçambique', 'capital' => 'Maputo'],
    ['country' => 'Mônaco', 'capital' => 'Mônaco'],
    ['country' => 'Mongólia', 'capital' => 'Ulan Bator'],
    ['country' => 'Montenegro', 'capital' => 'Podgorica'],
    ['country' => 'Namíbia', 'capital' => 'Windhoek'],
    ['country' => 'Nepal', 'capital' => 'Katmandu'],
    ['country' => 'Nicarágua', 'capital' => 'Manágua'],
    ['country' => 'Nigéria', 'capital' => 'Abuja'],
    ['country' => 'Noruega', 'capital' => 'Oslo'],
    ['country' => 'Nova Zelândia', 'capital' => 'Wellington'],
    ['country' => 'Países Baixos', 'capital' => 'Amsterdã'],
    ['country' => 'Paquistão', 'capital' => 'Islamabad'],
    ['country' => 'Panamá', 'capital' => 'Cidade do Panamá'],
    ['country' => 'Paraguai', 'capital' => 'Assunção'],
    ['country' => 'Peru', 'capital' => 'Lima'],
    ['country' => 'Polônia', 'capital' => 'Varsóvia'],
    ['country' => 'Portugal', 'capital' => 'Lisboa'],
    ['country' => 'Quênia', 'capital' => 'Nairóbi'],
    ['country' => 'Reino Unido', 'capital' => 'Londres'],
    ['country' => 'República Centro-Africana', 'capital' => 'Bangui'],
    ['country' => 'República Dominicana', 'capital' => 'Santo Domingo'],
    ['country' => 'República Tcheca', 'capital' => 'Praga'],
    ['country' => 'Romênia', 'capital' => 'Bucareste'],
    ['country' => 'Ruanda', 'capital' => 'Kigali'],
    ['country' => 'Rússia', 'capital' => 'Moscou'],
    ['country' => 'San Marino', 'capital' => 'San Marino'],
    ['country' => 'Santa Sé', 'capital' => 'Cidade do Vaticano'],
    ['country' => 'São Tomé e Príncipe', 'capital' => 'São Tomé'],
    ['country' => 'Senegal', 'capital' => 'Dacar'],
    ['country' => 'Sérvia', 'capital' => 'Belgrado'],
    ['country' => 'Singapura', 'capital' => 'Singapura'],
    ['country' => 'Síria', 'capital' => 'Damasco'],
    ['country' => 'Somália', 'capital' => 'Mogadíscio'],
    ['country' => 'Sri Lanka', 'capital' => 'Sri Jayawardenepura Kotte'],
    ['country' => 'Suécia', 'capital' => 'Estocolmo'],
    ['country' => 'Suíça', 'capital' => 'Berna'],
    ['country' => 'Suriname', 'capital' => 'Paramaribo'],
    ['country' => 'Tailândia', 'capital' => 'Bangkok'],
    ['country' => 'Taiwan', 'capital' => 'Taipé'],
    ['country' => 'Tanzânia', 'capital' => 'Dodoma'],
    ['country' => 'Togo', 'capital' => 'Lomé'],
    ['country' => 'Tunísia', 'capital' => 'Túnis'],
    ['country' => 'Turquia', 'capital' => 'Ancara'],
    ['country' => 'Ucrânia', 'capital' => 'Kyiv'],
    ['country' => 'Uganda', 'capital' => 'Campala'],
    ['country' => 'Uruguai', 'capital' => 'Montevidéu'],
    ['country' => 'Venezuela', 'capital' => 'Caracas'],
    ['country' => 'Vietnã', 'capital' => 'Hanói'],
    ['country' => 'Zâmbia', 'capital' => 'Lusaka'],
    ['country' => 'Zimbábue', 'capital' => 'Harare'],
];
